version: '0.1'
services:
  ras:
    image: ras:latest
    build: ./ras/
    ipc: host
    volumes:
      - ./ras/configs/test_avatar.yaml:/app/config.yaml
      - ./ras/stream_processing:/app/stream_processing
      - ./ras/logs:/app/logs
    ports:
      - 0.0.0.0:8887:8887
    environment:
      - ws_host=0.0.0.0
      - ws_port=8887

  rpm:
    image: rpm:latest
    build:
      context: ./rpm/
      args:
        REACT_APP_WS_URL: ws://0.0.0.0:8887
    volumes:
      - ./rpm/src:/app/src
      - ./rpm/public:/app/public
    ports:
     - 3000:3000
    environment:
     - CHOKIDAR_USEPOLLING=true