version: '0.1'
services:
  ras:
    image: ras:latest
    build: ./ras/
    volumes:
      - ./ras/configs/onnx_models.yaml:/app/config.yaml
      - ./ras/stream_processing:/app/stream_processing
      - ./ras/logs:/app/logs

  rpm:
    image: rpm:latest
    build: ./rpm/
    volumes:
      - ./rpm/src:/app/src
    ports:
     - 3000:3000
    environment:
     - CHOKIDAR_USEPOLLING=true