version: '0.1'
services:
  ras:
    image: ras:latest
    build: ./ras/
    ipc: host
    volumes:
      - ./ras/configs/onnx_models.yaml:/app/config.yaml
      - ./ras/stream_processing:/app/stream_processing
      - ./ras/logs:/app/logs
      - ./ras/onnx:/app/onnx
      - ./ras/target_feats:/app/target_feats
      - /Users/cafr02/repos/charite/clips/:/app/charite_clips
    ports:
      # port for the web socket service, to wich the react-app will connect:
      - 0.0.0.0:8888:8888

  rpm:
    image: rpm:latest
    build:
      context: ./rpm/
    volumes:
      - ./rpm/src:/app/src
      - ./rpm/public:/app/public
      - ./rpm/build:/app/build
    ports:
     - 3000:3000
    environment:
     - CHOKIDAR_USEPOLLING=true
     - WATCHPACK_POLLING=true
