log_dir: logs
log_level: INFO
define: &max_unsynced_time 0.01
define: &video_file J:/Datasets/LibriSpeech/dev-clean/8842/304647/8842-304647-0004.flac
define: &video_width 1280
define: &video_height 720

video:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  width: *video_width
  height: *video_height
  input_device: 0
  use_video: false
  processing_size: 1
  max_fps: 20
  output_virtual_cam: false
  output_window: false
  store: false
  store_format: "avi"
  converter:
    cls: stream_processing.models.Avatar
    width: *video_width
    height: *video_height
    ws_host: 0.0.0.0
    ws_port: 8888
    app_port: 3000
    avatar_renderer: opengl
    start_chrome_renderer: true
    use_chrome_extension: true
    show_renderer_window: false
    avatar_uri: ./default_avatar.glb

# audio:
#   max_unsynced_time: *max_unsynced_time
#   video_file: *video_file
#   use_audio: true
#   output_buffersize: 1200
#   processing_size: 9600
#   record_buffersize: 1200
#   sampling_rate: 16000
#   input_device: MacBook Pro-Mikrofon
#   output_device: MacBook Pro-Lautsprecher
#   store: false
#   converter:
#     cls: stream_processing.models.KnnVC
#     target_feats_path: ./target_feats/knnvc/john.pt
#     device: cpu
#     n_neighbors: 4
#     prev_audio_queue:
#       max_samples: 9600
#     interpolator:
#       n_samples: 450
#       weight: 0.75
#     vad:
#       frame_length: 2048
#       hop_length: 512
#       threshold: 0.010

audio:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  use_audio: true
  output_buffersize: 1920
  processing_size: 1920
  record_buffersize: 480
  sampling_rate: 24000
  input_device: MacBook Pro-Mikrofon
  output_device: MacBook Pro-Lautsprecher
  store: false
  converter:
    cls: stream_processing.models.MimiVC
    target_feats_path: ./target_feats/mimivc/1089.pt
    device: cpu
    n_neighbors: 4
    prev_audio_queue:
      max_samples: 9600
    prev_ctx:
      use_previous_ctx: false
      max_samples: 0
    lookahead_ctx:
    interpolator:
      n_samples: 450
      weight: 0.75
    vad:
      frame_length: 2048
      hop_length: 512
      threshold: 0.010
