log_dir: logs
log_level: INFO
define: &max_unsynced_time 0.01
define: &video_file /netscratch/fschulz/stream_processing/Test1.mp4
define: &video_width 1620
define: &video_height 1080

video:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  width: *video_width
  height: *video_height
  input_device: 0
  use_video: true
  processing_size: 1
  max_fps: 100
  output_virtual_cam: false
  output_window: false
  store: true
  store_format: "mp4"
  converter:
    cls: stream_processing.models.Avatar
    width: *video_width
    height: *video_height
    ws_host: 0.0.0.0
    ws_port: 8888
    app_port: 3000
    # select renderer for avatar: opengl | browser
    avatar_renderer: opengl
    start_chrome_renderer: true
    use_chrome_extension: true
    show_renderer_window: false

audio:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  use_audio: false
  output_buffersize: 600
  processing_size: 9600
  record_buffersize: 600
  sampling_rate: 16000
  input_device: MacBook Pro-Mikrofon
  output_device: MacBook Pro-Lautsprecher
  store: true
  converter:
    cls: stream_processing.models.Echo