log_dir: logs
log_level: INFO
define: &max_unsynced_time 0.01
define: &video_file ./videos/mourinho.mp4
define: &video_width 1280
define: &video_height 720

video:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  width: *video_width
  height: *video_height
  input_device: 0
  use_video: true
  processing_size: 1
  max_fps: 100
  output_virtual_cam: false
  output_window: false
  store: true
  store_format: "avi"
  converter:
    cls: stream_processing.models.Avatar
    width: *video_width
    height: *video_height

audio:
  max_unsynced_time: *max_unsynced_time
  video_file: *video_file
  use_audio: true
  output_buffersize: 600
  processing_size: 9600
  record_buffersize: 600
  sampling_rate: 16000
  input_device: MacBook Pro-Mikrofon
  output_device: MacBook Pro-Lautsprecher
  store: true
  converter:
    cls: stream_processing.models.Echo