log_dir: logs
log_level: DEBUG
max_unsynced_time: 0.01

video_callback:
  cls: stream_processing.models.face_mask.FaceMask.FaceMask

audio_callback:
  cls: stream_processing.models.knnvc.converter.Converter
  target_feats_path: target_feats/135887.pt
  device: cpu
  hifigan_cfg: /Users/cafr02/repos/spkanon/checkpoints/knnvc/hifigan.json
  hifigan_ckpt: /Users/cafr02/repos/spkanon/checkpoints/knnvc/hifigan.pt
  wavlm_ckpt: /Users/cafr02/repos/spkanon/checkpoints/WavLM-Large.pt
  wavlm_layer: 6
  n_neighbors: 4

video:
  input_device_index: 0
  use_video: True
  processing_size: 1
  maximum_fps: 20
  output_virtual_cam: false
  output_window: true

audio:
  use_audio: True
  output_buffersize: 600
  processing_size: 1200
  record_buffersize: 600
  sampling_rate: 16000
  input_device: MacBook Pro-Mikrofon
  output_device: BlackHole 2ch
