log_dir: logs
log_level: DEBUG
define: &max_unsynced_time 0.01

video:
  max_unsynced_time: *max_unsynced_time
  input_device: 0
  use_video: true
  processing_size: 1
  maximum_fps: 20
  output_virtual_cam: false
  output_window: true
  converter:
    cls: stream_processing.models.FaceMask

audio:
  max_unsynced_time: *max_unsynced_time
  use_audio: true
  output_buffersize: 600
  processing_size: 3200
  record_buffersize: 600
  sampling_rate: 16000
  input_device: MacBook Pro-Mikrofon
  output_device: BlackHole 2ch
  converter:
    cls: stream_processing.models.KnnVC
    target_feats_path: target_feats/135887.pt
    device: cpu
    hifigan_cfg: /Users/cafr02/repos/spkanon/checkpoints/knnvc/hifigan.json
    hifigan_ckpt: /Users/cafr02/repos/spkanon/checkpoints/knnvc/hifigan.pt
    wavlm_ckpt: /Users/cafr02/repos/spkanon/checkpoints/WavLM-Large.pt
    wavlm_layer: 6
    n_neighbors: 4
    prev_audio_queue:
      max_samples: 16000
    interpolator:
      n_samples: 200
      weight: 0.5
    vad:
      frame_length: 2048
      hop_length: 512
      threshold: 0.025
